### ISSUE TITLE
Readme.md

### ISSUE THREAD

**Issue by Mokerstier** [theonejonahgold/progressive-web-apps-2021#2]
Werk je readme even uit en neem ons daar mee in je .go strategie ik snap er werkelijk niks van ^^

**Comment by jonahgoldwastaken** [comment]
Ga ik zeker doen! Ik heb deze week heel hard gewerkt aan een static site generator die de top posts van hackernews met alle comments pre-rendered, een server voor lokaal development (die erg lijkt op express) die bij elke request data dynamisch inlaadt en een [serve](https://github.com/vercel/serve)-achtige implementatie voor als de site statisch is gegenereerd 😊

Ik ga dit rustig uitwerken in m'n readme, maar dacht ik geef je alvast een voorproefje (en daarbij hoop ik ook dat je begrijpt waarom ik 3 dagen niets heb gepusht).
